# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Overwrite a sparse matrix with its transpose
#' @param X A sparse matrix from R
#' @details Basic function that forces a transpose on a `arma::sp_mat` matrix without generating two full in memory.
inplace_transpose_sparse <- function(X) {
    invisible(.Call(`_acousticMove_inplace_transpose_sparse`, X))
}

#' Compute expAv
#' @param A A sparse matrix from R of \code{class(A) == "dgCMatrix"}.
#' @param v Vector (column vector) of to do exp(A)*v
#' @param tol Tolerance default = 1e-8.
#' @param renorm_freq Renoramlization frequency to avoid computational overload from rho^n/n!.
#' @param trans Logical to confirm if we should do transpose of A.
#' @details Implements Sherlock 2021 uniformization method.
expAv_cpp <- function(A, v, tol, renorm_freq, trans = FALSE) {
    .Call(`_acousticMove_expAv_cpp`, A, v, tol, renorm_freq, trans)
}

#' Compute expAv'
#' @param A A sparse matrix from R of \code{class(A) == "dgCMatrix"}.
#' @param dv Matrix of dv/dtheta for expAv', with nrows = nrow(A) and ncols = length(theta) to compute exp(A)*dv.
#' @param tol Tolerance default = 1e-8.
#' @param renorm_freq Renoramlization frequency to avoid computational overload from rho^n/n!.
#' @param trans Logical to confirm if we should do transpose of A.
#' @details Implements Sherlock 2021 uniformization method, simply a version of expAv that allows for v to be a matrix.
expAdv_cpp <- function(A, dv, tol, renorm_freq, trans = FALSE) {
    .Call(`_acousticMove_expAdv_cpp`, A, dv, tol, renorm_freq, trans)
}

#' Fast Multiply of multiple sparse matrix vector.
#' @param dA Dense matrix with each column the non-zero values of a sparse matrix.
#' @param term Vector to multiply against matrix.
#' @param row_indx Row index from column-sparse matrix "dgCMatrix" \code{A@i}.
#' @param col_ptr Column pointer from column-sparse matrix "dgCMatrix" \code{A@p}.
fast_multiply <- function(dA, term, row_indx, col_ptr) {
    .Call(`_acousticMove_fast_multiply`, dA, term, row_indx, col_ptr)
}

#' Compute expAv and gradient of expAv jointly
#' @param A A sparse matrix from R of \code{class(A) == "dgCMatrix"}.
#' @param dA A matrix that has row of non-zero gradient of A and columns for each parameter.
#' @param v Vector (column vector) of to do exp(A)*v
#' @param tol Tolerance default = 1e-8.
#' @param renorm_freq Renoramlization frequency to avoid computational overload from rho^n/n!.
#' @param trans Logical to confirm if we should do transpose of A.
#' @param row_indx Row index from column-sparse matrix "dgCMatrix" \code{A@i}.
#' @param col_ptr Column pointer from column-sparse matrix "dgCMatrix" \code{A@p}.
#' @details Computes joint expAv and the gradient as implemented in 'Differentiated uniformization: a new method for inferring Markov chains on combinatorial state spaces including stochastic epidemic models'.
expAv_gr_cpp <- function(A, dA, v, tol, renorm_freq, row_indx, col_ptr) {
    .Call(`_acousticMove_expAv_gr_cpp`, A, dA, v, tol, renorm_freq, row_indx, col_ptr)
}

#' Compute Linear approximation of expAv and gradient of expAv jointly
#' @param A A sparse matrix from R of \code{class(A) == "dgCMatrix"}.
#' @param v Vector (column vector) of to do exp(A)*v.
#' @param lambda Vector (column vector) of detection rate.
#' @param tol Tolerance default = 1e-8.
#' @param trans Logical to confirm if we should do transpose of A.
#' @details Computes joint expAv and the gradient as implemented in 'Differentiated uniformization: a new method for inferring Markov chains on combinatorial state spaces including stochastic epidemic models'.
expAv_approx_cpp <- function(A, v, lambda, tol) {
    .Call(`_acousticMove_expAv_approx_cpp`, A, v, lambda, tol)
}

