# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

expAv_cpp <- function(A, v, tol, renorm_freq, forward) {
    .Call(`_acousticMove_expAv_cpp`, A, v, tol, renorm_freq, forward)
}

